/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rodriguez;

/**
 *
 * @author lenovo
 */
public class calculadora extends javax.swing.JFrame {
    
   
    public float primernumero;
    public float segundonumero;
    public String operador;

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casilla_lcrp = new javax.swing.JLabel();
        c_lcrp = new javax.swing.JButton();
        menos_lcrp = new javax.swing.JButton();
        dividido_lcrp = new javax.swing.JButton();
        por_lcrp = new javax.swing.JButton();
        tres_lcrp = new javax.swing.JButton();
        igual_lcrp = new javax.swing.JButton();
        dos_lcrp = new javax.swing.JButton();
        uno_lcrp = new javax.swing.JButton();
        cero_lcrp = new javax.swing.JButton();
        punto_lcrp = new javax.swing.JButton();
        siete_lcrp = new javax.swing.JButton();
        ocho_lcrp = new javax.swing.JButton();
        nueve_lcrp = new javax.swing.JButton();
        mas_lcrp = new javax.swing.JButton();
        cuatro_lcrp = new javax.swing.JButton();
        cinco_lcrp = new javax.swing.JButton();
        seis_lcrp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        casilla_lcrp.setBackground(new java.awt.Color(255, 255, 255));
        casilla_lcrp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        casilla_lcrp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        casilla_lcrp.setOpaque(true);

        c_lcrp.setText("c");
        c_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_lcrpActionPerformed(evt);
            }
        });

        menos_lcrp.setText("-");
        menos_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_lcrpActionPerformed(evt);
            }
        });

        dividido_lcrp.setText("/");
        dividido_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividido_lcrpActionPerformed(evt);
            }
        });

        por_lcrp.setText("*");
        por_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                por_lcrpActionPerformed(evt);
            }
        });

        tres_lcrp.setText("3");
        tres_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tres_lcrpActionPerformed(evt);
            }
        });

        igual_lcrp.setText("=");
        igual_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igual_lcrpActionPerformed(evt);
            }
        });

        dos_lcrp.setText("2");
        dos_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dos_lcrpActionPerformed(evt);
            }
        });

        uno_lcrp.setText("1");
        uno_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uno_lcrpActionPerformed(evt);
            }
        });

        cero_lcrp.setText("0");
        cero_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cero_lcrpActionPerformed(evt);
            }
        });

        punto_lcrp.setText(".");
        punto_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto_lcrpActionPerformed(evt);
            }
        });

        siete_lcrp.setText("7");
        siete_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siete_lcrpActionPerformed(evt);
            }
        });

        ocho_lcrp.setText("8");
        ocho_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocho_lcrpActionPerformed(evt);
            }
        });

        nueve_lcrp.setText("9");
        nueve_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueve_lcrpActionPerformed(evt);
            }
        });

        mas_lcrp.setText("+");
        mas_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mas_lcrpActionPerformed(evt);
            }
        });

        cuatro_lcrp.setText("4");
        cuatro_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatro_lcrpActionPerformed(evt);
            }
        });

        cinco_lcrp.setText("5");
        cinco_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinco_lcrpActionPerformed(evt);
            }
        });

        seis_lcrp.setText("6");
        seis_lcrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seis_lcrpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(casilla_lcrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(c_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dividido_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(por_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(menos_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(siete_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ocho_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nueve_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cuatro_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cinco_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(seis_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(mas_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cero_lcrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(punto_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(uno_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dos_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tres_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(igual_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(casilla_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dividido_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(por_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menos_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siete_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocho_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nueve_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuatro_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cinco_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seis_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mas_lcrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uno_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dos_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tres_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cero_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(punto_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(igual_lcrp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void igual_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igual_lcrpActionPerformed
     this.segundonumero=Float.parseFloat(this.casilla_lcrp.getText());
     switch(this.operador){
         case "+":this.casilla_lcrp.setText(sincero(this.primernumero+this.segundonumero));break;
         case "-":this.casilla_lcrp.setText(sincero(this.primernumero-this.segundonumero));break;
         case "*":this.casilla_lcrp.setText(sincero(this.primernumero*this.segundonumero));break;
         case "/":if(this.segundonumero==0){this.casilla_lcrp.setText("No_Se_Divide_Entre_0");}
         else{
                 this.casilla_lcrp.setText(sincero(this.primernumero/this.segundonumero));}break;
     }
             
    }//GEN-LAST:event_igual_lcrpActionPerformed

    private void menos_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_lcrpActionPerformed
    this.primernumero=Float.parseFloat(this.casilla_lcrp.getText());
    this.operador= "-";
    this.casilla_lcrp.setText("");
    }//GEN-LAST:event_menos_lcrpActionPerformed

    private void por_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_por_lcrpActionPerformed
    this.primernumero=Float.parseFloat(this.casilla_lcrp.getText());
    this.operador= "*";
    this.casilla_lcrp.setText("");
    }//GEN-LAST:event_por_lcrpActionPerformed

    private void c_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_lcrpActionPerformed
    this.casilla_lcrp.setText(" ");
    }//GEN-LAST:event_c_lcrpActionPerformed

    private void uno_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uno_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"1");
    }//GEN-LAST:event_uno_lcrpActionPerformed

    private void ocho_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocho_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"8");
    }//GEN-LAST:event_ocho_lcrpActionPerformed

    private void nueve_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueve_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"9");
    }//GEN-LAST:event_nueve_lcrpActionPerformed

    private void cero_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cero_lcrpActionPerformed
 this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"0");
    }//GEN-LAST:event_cero_lcrpActionPerformed

    private void dos_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dos_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"2");
    }//GEN-LAST:event_dos_lcrpActionPerformed

    private void tres_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tres_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"3");
    }//GEN-LAST:event_tres_lcrpActionPerformed

    private void cuatro_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatro_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"4");
    }//GEN-LAST:event_cuatro_lcrpActionPerformed

    private void cinco_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinco_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"5");
    }//GEN-LAST:event_cinco_lcrpActionPerformed

    private void seis_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seis_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"6");
    }//GEN-LAST:event_seis_lcrpActionPerformed

    private void siete_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siete_lcrpActionPerformed
    this.casilla_lcrp.setText(this.casilla_lcrp.getText()+"7");
    }//GEN-LAST:event_siete_lcrpActionPerformed

    private void mas_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mas_lcrpActionPerformed
    this.primernumero=Float.parseFloat(this.casilla_lcrp.getText());
    this.operador= "+";
    this.casilla_lcrp.setText("");
    }//GEN-LAST:event_mas_lcrpActionPerformed

    private void dividido_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividido_lcrpActionPerformed
    this.primernumero=Float.parseFloat(this.casilla_lcrp.getText());
    this.operador= "/";
    this.casilla_lcrp.setText("");
    }//GEN-LAST:event_dividido_lcrpActionPerformed

    private void punto_lcrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto_lcrpActionPerformed
     if(!(this.casilla_lcrp.getText().contains("."))){
     this.casilla_lcrp.setText(this.casilla_lcrp.getText()+".");   
     }
    }//GEN-LAST:event_punto_lcrpActionPerformed

    public String sincero(float resultado){
        String retorno="";
        retorno=Float.toString(resultado);
        if(resultado%1==0){
           retorno=retorno.substring(0,retorno.length()-2);
        }    
        return retorno;
     }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_lcrp;
    private javax.swing.JLabel casilla_lcrp;
    private javax.swing.JButton cero_lcrp;
    private javax.swing.JButton cinco_lcrp;
    private javax.swing.JButton cuatro_lcrp;
    private javax.swing.JButton dividido_lcrp;
    private javax.swing.JButton dos_lcrp;
    private javax.swing.JButton igual_lcrp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mas_lcrp;
    private javax.swing.JButton menos_lcrp;
    private javax.swing.JButton nueve_lcrp;
    private javax.swing.JButton ocho_lcrp;
    private javax.swing.JButton por_lcrp;
    private javax.swing.JButton punto_lcrp;
    private javax.swing.JButton seis_lcrp;
    private javax.swing.JButton siete_lcrp;
    private javax.swing.JButton tres_lcrp;
    private javax.swing.JButton uno_lcrp;
    // End of variables declaration//GEN-END:variables
}
